#!/bin/bash

up() {
    case $(xdotool get_desktop) in
        0) wmctrl -s 9 ;;
        *) wmctrl -s $(expr `xdotool get_desktop` - 1) ;;
    esac
}

down() {
    case $(xdotool get_desktop) in
        9) wmctrl -s 0 ;;
        *) wmctrl -s $(expr `xdotool get_desktop` + 1) ;;
    esac
}

case $1 in
    up) up ;;
    down) down ;;
esac
