#!/bin/bash

cache_dir="$HOME/.cache/eww/weather"
cache_weather_location=${cache_dir}/weather-location

get_icon() {
    if [ "$(date +%H)" -ge "18" ] || [ "$(date +%H)" -le "0" ]; then
        curl "wttr.in/~"$(cat ${cache_weather_location})"?u&format=%m"
    elif [ "$(date +%H)" -ge "6" ]; then
        curl "wttr.in/~"$(cat ${cache_weather_location})"?u&format=%c"
    else
        curl "wttr.in/~"$(cat ${cache_weather_location})"?u&format=%m"
    fi
}

case $1 in
    --temp) curl "wttr.in/~"$(cat ${cache_weather_location})"?u&format=%t" ;;
    --icon) get_icon ;;
esac
