#! /bin/bash

#define icons for workspaces 1-9
ic=(0     輸    )

#initial check for occupied workspaces
initialcheck() {
for num in $(hyprctl -j workspaces | jaq -r '.[].id'); do
  export o"$num"="occupied"
done
 
#initial check for focused workspace
for num in $(hyprctl -j monitors | jaq -r '.[] | select(.focused == true) | .activeWorkspace.id'); do
  export f"$num"="focused"
  export fnum=f"$num"
  export mon=$(hyprctl -j monitors | jaq -r ".[] | select(.activeWorkspace.id == $num) | .name")
done
}

workspaces() {
if [[ ${1:0:9} == "workspace" ]]; then #set focused workspace
  unset -v "$fnum" 
  num=${1:11}
  export f"$num"="focused"
  export fnum=f"$num"

elif [[ ${1:0:10} == "focusedmon" ]]; then #set focused workspace following monitor focus change
  unset -v "$fnum"
  string=${1:12}
  num=${string##**,}
  export mon=${string/,*/}
  export f"$num"="focused"
  export fnum=f"$num"

elif [[ ${1:0:13} == "moveworkspace" ]] && [[ ${1##*,} == "$mon" ]]; then #Set focused workspace following swapactiveworkspace
  unset -v "$fnum"
  string=${1:15}
  num=${string/,*/}
  export f"$num"="focused"
  export fnum=f"$num"

elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
  num=${1:17}
  export o"$num"="occupied"
  export onum=o"$num"

elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
  num=${1:18}
  unset -v o"$num"
fi
}

module() {
#output eww widget
echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"h\" :spacing 1 :space-evenly \"false\" \
              (button :onclick \"hyprctl dispatch exec \'~/.local/share/cargo/bin/hyprsome workspace 1\'\" :onrightclick \"hyprctl dispatch workspace 11\" :class \"ws-11 $o11 $f11 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec \'~/.local/share/cargo/bin/hyprsome workspace 2\'\" :onrightclick \"hyprctl dispatch workspace 12\" :class \"ws-12 $o12 $f12 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec \'~/.local/share/cargo/bin/hyprsome workspace 3\'\" :onrightclick \"hyprctl dispatch workspace 13\" :class \"ws-13 $o13 $f13 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec \'~/.local/share/cargo/bin/hyprsome workspace 4\'\" :onrightclick \"hyprctl dispatch workspace 14\" :class \"ws-14 $o14 $f14 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec \'~/.local/share/cargo/bin/hyprsome workspace 5\'\" :onrightclick \"hyprctl dispatch workspace 15\" :class \"ws-15 $o15 $f15 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec \'~/.local/share/cargo/bin/hyprsome workspace 6\'\" :onrightclick \"hyprctl dispatch workspace 16\" :class \"ws-16 $o16 $f16 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec \'~/.local/share/cargo/bin/hyprsome workspace 7\'\" :onrightclick \"hyprctl dispatch workspace 17\" :class \"ws-17 $o17 $f17 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec \'~/.local/share/cargo/bin/hyprsome workspace 8\'\" :onrightclick \"hyprctl dispatch workspace 18\" :class \"ws-18 $o18 $f18 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec \'~/.local/share/cargo/bin/hyprsome workspace 9\'\" :onrightclick \"hyprctl dispatch workspace 19\" :class \"ws-19 $o19 $f19 workspacebuttons\" \" \") \
          )\
        )"
}

# actually running things
initialcheck
module

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
module
done
