#! /bin/bash

#define icons for workspaces 1-9
ic=(0     輸    )

#initial check for occupied workspaces
initialcheck() {
for num in $(hyprctl -j workspaces | jaq -r '.[].id' | sed '/^-/d'); do
  export o"$num"="occupied"
done
 
#initial check for focused workspace
for num in $(hyprctl -j monitors | jaq -r '.[] | select(.focused == true) | .activeWorkspace.id'); do
  export f"$num"="focused"
  export fnum=f"$num"
  export mon=$(hyprctl -j monitors | jaq -r ".[] | select(.activeWorkspace.id == $num) | .name")
done
}

workspaces() {
if [[ ${1:0:9} == "workspace" ]]; then #set focused workspace
  unset -v "$fnum" 
  num=${1:11}
  export f"$num"="focused"
  export fnum=f"$num"

elif [[ ${1:0:10} == "focusedmon" ]]; then #set focused workspace following monitor focus change
  unset -v "$fnum"
  string=${1:12}
  num=${string##**,}
  export mon=${string/,*/}
  export f"$num"="focused"
  export fnum=f"$num"

elif [[ ${1:0:13} == "moveworkspace" ]] && [[ ${1##*,} == "$mon" ]]; then #Set focused workspace following swapactiveworkspace
  unset -v "$fnum"
  string=${1:15}
  num=${string/,*/}
  export f"$num"="focused"
  export fnum=f"$num"

elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
  num=${1:17}
  export o"$num"="occupied"
  export onum=o"$num"

elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
  num=${1:18}
  unset -v o"$num"
fi
}

module() {
#output eww widget
echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"h\" :spacing 0 :space-evenly \"false\" \
              (button :onclick \"hyprctl dispatch exec '~/.config/hypr/hyprworkspace.sh workspace' 1\" :class \"ws-21 $o21 $f21 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec '~/.config/hypr/hyprworkspace.sh workspace' 2\" :class \"ws-22 $o22 $f22 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec '~/.config/hypr/hyprworkspace.sh workspace' 3\" :class \"ws-23 $o23 $f23 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec '~/.config/hypr/hyprworkspace.sh workspace' 4\" :class \"ws-24 $o24 $f24 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec '~/.config/hypr/hyprworkspace.sh workspace' 5\" :class \"ws-25 $o25 $f25 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec '~/.config/hypr/hyprworkspace.sh workspace' 6\" :class \"ws-26 $o26 $f26 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec '~/.config/hypr/hyprworkspace.sh workspace' 7\" :class \"ws-27 $o27 $f27 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec '~/.config/hypr/hyprworkspace.sh workspace' 8\" :class \"ws-28 $o28 $f28 workspacebuttons\" \" \") \
              (button :onclick \"hyprctl dispatch exec '~/.config/hypr/hyprworkspace.sh workspace' 9\" :class \"ws-29 $o29 $f29 workspacebuttons\" \" \") \
          )\
        )"
}

# actually running things
initialcheck
module

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
module
done
