#!/bin/bash

workspaces() {
ws1=1
ws2=2
ws3=3
ws4=4
ws5=5
ws6=6
ws7=7
ws8=8
ws9=9

# unoccupied
un="0"

# occupied
o1=$(bspc query -D -d .occupied --names | grep -Ev "[0-9]{2}" | grep "$ws1" || echo "0")
o2=$(bspc query -D -d .occupied --names | grep -Ev "[0-9]{2}" | grep "$ws2" || echo "0")
o3=$(bspc query -D -d .occupied --names | grep -Ev "[0-9]{2}" | grep "$ws3" || echo "0")
o4=$(bspc query -D -d .occupied --names | grep -Ev "[0-9]{2}" | grep "$ws4" || echo "0")
o5=$(bspc query -D -d .occupied --names | grep -Ev "[0-9]{2}" | grep "$ws5" || echo "0")
o6=$(bspc query -D -d .occupied --names | grep -Ev "[0-9]{2}" | grep "$ws6" || echo "0")
o7=$(bspc query -D -d .occupied --names | grep -Ev "[0-9]{2}" | grep "$ws7" || echo "0")
o8=$(bspc query -D -d .occupied --names | grep -Ev "[0-9]{2}" | grep "$ws8" || echo "0")
o9=$(bspc query -D -d .occupied --names | grep -Ev "[0-9]{2}" | grep "$ws9" || echo "0")

# focused
f1=$(bspc query -D -d focused --names | grep -Ev "[0-9]{2}" | grep "$ws1")
f2=$(bspc query -D -d focused --names | grep -Ev "[0-9]{2}" | grep "$ws2")
f3=$(bspc query -D -d focused --names | grep -Ev "[0-9]{2}" | grep "$ws3")
f4=$(bspc query -D -d focused --names | grep -Ev "[0-9]{2}" | grep "$ws4")
f5=$(bspc query -D -d focused --names | grep -Ev "[0-9]{2}" | grep "$ws5")
f6=$(bspc query -D -d focused --names | grep -Ev "[0-9]{2}" | grep "$ws6")
f7=$(bspc query -D -d focused --names | grep -Ev "[0-9]{2}" | grep "$ws7")
f8=$(bspc query -D -d focused --names | grep -Ev "[0-9]{2}" | grep "$ws8")
f9=$(bspc query -D -d focused --names | grep -Ev "[0-9]{2}" | grep "$ws9")

echo "(eventbox :onscroll \"${HOME}/.config/eww/scripts/scrollworkspace0 {}\" (box :class \"workspaces\" :orientation \"h\" :space-evenly true :halign \"start\" :spacing 10 (button :onclick \"wmctrl -s 10\" :class \"$un$o1$f1\" \"\") (button :onclick \"wmctrl -s 11\" :class \"$un$o2$f2\" \"\") (button :onclick \"wmctrl -s 12\" :class \"$un$o3$f3\" \"\") (button :onclick \"wmctrl -s 13\" :class \"$un$o4$f4\" \"\") (button :onclick \"wmctrl -s 14\" :class \"$un$o5$f5\" \"\") (button :onclick \"wmctrl -s 15\" :class \"$un$o6$f6\" \"\") (button :onclick \"wmctrl -s 16\" :class \"$un$o7$f7\" \"\") (button :onclick \"wmctrl -s 17\" :class \"$un$o8$f8\" \"\") (button :onclick \"wmctrl -s 18\" :class \"$un$o9$f9\" \" \")))"
}

workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
workspaces
done
