#!/bin/bash

## Files and cmd
EWW="eww"
focusmon=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .id')

## Kill eww so that it reloads
killall eww

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	${EWW} daemon
	sleep 1
fi

## Send a notification so the notification sidepanel can get it
notify-send -t 500 "EWW" "Hi"

## Open widgets 
NB_MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))
for id in "${NB_MONITORS[@]}"; do
    hyprctl dispatch focusmonitor "$id"
    ${EWW} open "bar$id"
    ${EWW} open "workspacebar$id"
    [[ $id == 0 ]] && ${EWW} open notifications
done

    hyprctl dispatch focusmonitor "$focusmon"
