#! /bin/sh

# Autostarting Things
DISPLAY=:10 /home/jackson/.config/bspwm/rootful/autostart.sh &
pgrep -x sxhkd > /dev/null || sxhkd -c /home/jackson/.config/bspwm/rootful/sxhkdrc &

# Default BSPWM Stuff
bspc monitor XWAYLAND0 -d 1 2 3 4 5 6 7 8 9 10

bspc config automatic_scheme alternate

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#282a36"
bspc config focused_border_color "#808080"
bspc config presel_feedback_color "#008B8B"

bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

xsetroot -cursor_name left_ptr
